# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PushService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PushService

end

target 'TrackPushEvent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrackPushEvent

  pod 'SensorsAnalyticsSDK'

end
